#!/usr/bin/python
import os 
import typer
from typing import Optional
import subprocess
import time
import json
import requests
from rich import print
from rich.console import Console
from subprocess import DEVNULL, STDOUT, check_call

# Initialize and Setup Variables

console = Console()
username = os.popen("whoami").read()[:-1]
f = open(f"/home/{username}/.config/openbox/themes/.current")
activetheme = f.read().strip('\n')
f.close()
width = os.get_terminal_size().columns
cli = typer.Typer(add_completion=False)

# Information Command

@cli.command(help="Displays information for the chosen theme.")
def info(
    theme: str = typer.Option(
        activetheme,
        "-t",
        "--theme",
        help="Theme to fetch info for.",
    ),
):  # Open themes file and parse
    f = open('themes.json')
    data = json.load(f)
    # Print Information
    console.print(f"{data[theme]['name']}", style="bold")
    console.print(f"├─ {data[theme]['description']}")
    console.print(f"├─ Author: {data[theme]['author']}")
    console.print(f"├─ File Size: {data[theme]['size']}")
    console.print(f"├─ WM: {data[theme]['wm']}")
    console.print(f"├─ Launcher: {data[theme]['launcher']}")
    console.print(f"├─ Bar: {data[theme]['bar']}")
    console.print(f"├─ Dock: {data[theme]['dock']}")
    # Ultra Spaghetti Code
    console.print(f"└─ [{data[theme]['black']}]████[{data[theme]['red']}]████[{data[theme]['green']}]████[{data[theme]['yellow']}]████[{data[theme]['blue']}]████[{data[theme]['magenta']}]████[{data[theme]['cyan']}]████[{data[theme]['white']}]████")
    console.print(f"   [{data[theme]['black']}]████[{data[theme]['red']}]████[{data[theme]['green']}]████[{data[theme]['yellow']}]████[{data[theme]['blue']}]████[{data[theme]['magenta']}]████[{data[theme]['cyan']}]████[{data[theme]['white']}]████")

# Download and Install Theme Command
@cli.command(help="Downloads and installs the chosen theme.")
def download(
    theme: str = typer.Option(
        ...,
        "-t",
        "--theme",
        help="Theme to download and install.",
    ),
):  # Open themes file and parse
    f = open('themes.json')
    data = json.load(f)
    # Print status of script
    # Each subproccess.run is doing something to install/download the script
    console.print('[*] Downloading theme...', style="bold")
    r = requests.get(data[theme]['downloadlink'], allow_redirects=True)
    open('temp.tar.gz', 'wb').write(r.content)
    console.print('[*] Installing theme...', style="bold")
    subprocess.run(['mkdir temp && tar -xzvf temp.tar.gz -C temp --strip-components=1 && cd temp && bash install.sh >/dev/null 2>&1'], shell=True, stdout=DEVNULL, stderr=STDOUT)

    console.print('[*] Applying theme...', style="bold")
    subprocess.run([f'nohup bash /home/{username}/.config/openbox-themes/themes/{theme}/apply.sh & >/dev/null 2>&1'], shell=True, stdout=DEVNULL, stderr=STDOUT)
    time.sleep(5)
    subprocess.run([f'nohup bash /home/{username}/.config/openbox-themes/themes/{theme}/apply.sh & >/dev/null 2>&1'], shell=True, stdout=DEVNULL, stderr=STDOUT)

    console.print('[*] Cleaning up...', style="bold")
    subprocess.run(['rm -r -f temp temp.tar.gz nohup.out >/dev/null 2>&1'], shell=True, stdout=DEVNULL, stderr=STDOUT)
    # Print Information
    console.print('[*] All done, enjoy your new theme!', style="bold")
    console.print('[*] Check out some stats about it below! \n', style="bold")
    console.print(f"{data[theme]['name']}", style="bold")
    console.print(f"├─ {data[theme]['description']}")
    console.print(f"├─ Author: {data[theme]['author']}")
    console.print(f"├─ File Size: {data[theme]['size']}")
    console.print(f"├─ WM: {data[theme]['wm']}")
    console.print(f"├─ Launcher: {data[theme]['launcher']}")
    console.print(f"├─ Bar: {data[theme]['bar']}")
    console.print(f"├─ Dock: {data[theme]['dock']}")
    # Ultra Spaghetti Code
    console.print(f"└─ [{data[theme]['black']}]████[{data[theme]['red']}]████[{data[theme]['green']}]████[{data[theme]['yellow']}]████[{data[theme]['blue']}]████[{data[theme]['magenta']}]████[{data[theme]['cyan']}]████[{data[theme]['white']}]████")
    console.print(f"   [{data[theme]['black']}]████[{data[theme]['red']}]████[{data[theme]['green']}]████[{data[theme]['yellow']}]████[{data[theme]['blue']}]████[{data[theme]['magenta']}]████[{data[theme]['cyan']}]████[{data[theme]['white']}]████")  


cli()
